### ISSUE TITLE
How long does it take for plugins to get updated?

### ISSUE THREAD

**Issue by lumbar527** [endless-sky/endless-sky-plugins#1004]
My plugin, es-ui-upgrades, has been updated with several commits multiple days ago. It has not been updated on the plugin list. Is this to be expected?

**Comment by warp-core** [comment]
It looks like it didn't know what branch to look for so the script to look for the updates wasn't working.
I think https://github.com/endless-sky/endless-sky-plugins/commit/e8f8a46520920b8a9ba997fc965aa39c51df91ac should have fixed it.
We'll find out the next time the script runs (in about 5 minutes.)

**Comment by warp-core** [comment]
Scratch that. It looks like the workflows run at quarter past every hour (in normal timezones, anyway.) So we'll find out in about 10 minutes.

**Comment by warp-core** [comment]
#1005 it worked!

**Comment by lumbar527** [comment]
Great, thanks!

**Comment by MCOfficer** [comment]
this shouldn't be necessary if we were following the RFC and using the default branch, but https://github.com/jelmer/dulwich/issues/863 forces us to just assume master instead.
