### ISSUE TITLE
Version tag with no major version number causes AutoUpdate to fail. 

### ISSUE THREAD

**Issue by Pshy0** [endless-sky/endless-sky-plugins#1086]
Autoupdate is failing on updating [A Coalition At War](https://github.com/mathwhiz1212/A-Coalition-At-War)
![image](https://github.com/endless-sky/endless-sky-plugins/assets/44928041/990e2d2c-6df1-4ba1-99dc-6e9c07726b90)

It could be cause by it's latest tag **v.10.0.1a** (no number between `v` and `.`):
![image](https://github.com/endless-sky/endless-sky-plugins/assets/44928041/61f27e6d-993f-4d62-8c1d-07a4ec1bc209)

**Comment by MCOfficer** [comment]
Thanks for noticing, i've patched it with f8e294970125ac682291b17d23ff567b98998ead, discussion is ongoing in #1087
